import { Alert } from '@/types';

export const alerts: Alert[] = [
    {
        id: 'alert-1',
        title: 'Instagram Engagement Drop',
        description: 'Engagement rate dropped below 3% threshold on Instagram for 3 consecutive days.',
        channel: 'instagram',
        severity: 'high',
        status: 'active',
        metric: 'Engagement Rate',
        threshold: 3.0,
        currentValue: 2.4,
        createdAt: '2026-03-04T10:00:00Z',
    },
    {
        id: 'alert-2',
        title: 'LinkedIn Impressions Spike',
        description: 'Post impressions exceeded 150% of weekly average. Viral content detected.',
        channel: 'linkedin',
        severity: 'low',
        status: 'active',
        metric: 'Impressions',
        threshold: 15000,
        currentValue: 28000,
        createdAt: '2026-03-04T08:00:00Z',
    },
    {
        id: 'alert-3',
        title: 'WhatsApp Delivery Rate Warning',
        description: 'Message delivery rate fell below 90% threshold.',
        channel: 'whatsapp',
        severity: 'medium',
        status: 'active',
        metric: 'Delivery Rate',
        threshold: 90,
        currentValue: 84,
        createdAt: '2026-03-03T14:30:00Z',
    },
    {
        id: 'alert-4',
        title: 'Instagram Follower Milestone',
        description: 'Reached 28,000 followers — 12% growth this quarter.',
        channel: 'instagram',
        severity: 'low',
        status: 'resolved',
        metric: 'Followers',
        threshold: 28000,
        currentValue: 28400,
        createdAt: '2026-03-02T09:00:00Z',
        resolvedAt: '2026-03-02T09:15:00Z',
    },
    {
        id: 'alert-5',
        title: 'LinkedIn CTR Below Target',
        description: 'Click-through rate on LinkedIn posts is below 1.5% target.',
        channel: 'linkedin',
        severity: 'medium',
        status: 'active',
        metric: 'CTR',
        threshold: 1.5,
        currentValue: 1.1,
        createdAt: '2026-03-01T11:00:00Z',
    },
    {
        id: 'alert-6',
        title: 'WhatsApp Response Time Alert',
        description: 'Average response time exceeded 30 minute threshold.',
        channel: 'whatsapp',
        severity: 'high',
        status: 'resolved',
        metric: 'Response Time',
        threshold: 30,
        currentValue: 42,
        createdAt: '2026-02-28T16:00:00Z',
        resolvedAt: '2026-03-01T08:00:00Z',
    },
    {
        id: 'alert-7',
        title: 'YouTube Views Surge',
        description: 'Video views exceeded 200% of weekly average. Viral content detected on Shorts.',
        channel: 'youtube',
        severity: 'low',
        status: 'active',
        metric: 'Views',
        threshold: 50000,
        currentValue: 128000,
        createdAt: '2026-03-04T12:00:00Z',
    },
    {
        id: 'alert-8',
        title: 'YouTube Watch Time Drop',
        description: 'Average view duration dropped below 3 minute threshold for long-form videos.',
        channel: 'youtube',
        severity: 'medium',
        status: 'active',
        metric: 'Avg View Duration',
        threshold: 180,
        currentValue: 145,
        createdAt: '2026-03-03T09:00:00Z',
    },
];
